server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost/db_msuser?serverTimezone=America/Lima&useSSL=false
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: debug