server:
  port: 8090
#Conexion a Postgres
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallpaper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
#Propiedades de JPA  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
#Definir el tamaño de subida de imagenes
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#Log de consultas
logging:
  level:
    org:
      hibernate:
        SQL: debug
#String de conexion al Azure Blob storage
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=accountimage;AccountKey=Ie9qI1wTOI+1UK079gxPj6iMw3A+6wq/qKeJWOQU3RqsB1yoNXdkOmnO77C6XYX7xKbrjlqOFZOH+ASt7bcmmQ==;EndpointSuffix=core.windows.net
